#!/bin/sh

unset GATEWAY_INTERFACE
unset REMOTE_HOST
unset REMOTE_ADDR
unset SHLVL
unset QUERY_STRING
unset HTTP_USER_AGENT
unset DOCUMENT_ROOT
unset REMOTE_PORT
unset HTTP_ACCEPT
unset SCRIPT_FILENAME
unset HTTP_HOST
unset REQUEST_URI
unset SERVER_SOFTWARE
unset HTTP_CONNECTION
unset HTTP_ACCEPT_LANGUAGE
unset SERVER_PROTOCOL
unset HTTP_ACCEPT_ENCODING
unset REDIRECT_STATUS
unset REQUEST_METHOD
unset SERVER_ADDR
unset PWD
unset SERVER_PORT
unset SCRIPT_NAME
unset SERVER_NAME

export HOME=/root
export USER=root
export LOGNAME=root

cd /
